context("Errors")

test_that("captures and stores errors", {
  stop("Error")  
})